// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PF_THEBEAVERS.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220806215000_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Models.Averias", b =>
                {
                    b.Property<int>("AveriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoAveriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AveriaId");

                    b.ToTable("Averias");
                });

            modelBuilder.Entity("Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "",
                            Cedula = "",
                            Nombre = "Cliente No Registrado"
                        });
                });

            modelBuilder.Entity("Models.Contratos", b =>
                {
                    b.Property<int?>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Existente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoContrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoReferencial")
                        .HasColumnType("TEXT");

                    b.Property<int>("UltimoPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContratoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Models.Pagos", b =>
                {
                    b.Property<int?>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CedulaCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Existente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<float?>("MontoPago")
                        .HasColumnType("REAL");

                    b.Property<string>("NoContrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPagoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PagoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Models.Planes", b =>
                {
                    b.Property<int?>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoPlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Descripcion = "3 Mbps/1 Mbps + 150 canales",
                            Estado = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5020),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5023),
                            Nombre = "Combo Básico",
                            Precio = 1000f,
                            TipoPlan = "Plan Básico",
                            TipoPlanId = 1
                        },
                        new
                        {
                            PlanId = 2,
                            Descripcion = "10 Mbps/3 Mbps + 175 canales",
                            Estado = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5240),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5242),
                            Nombre = "Combo Medio",
                            Precio = 1700f,
                            TipoPlan = "Plan Medio",
                            TipoPlanId = 2
                        },
                        new
                        {
                            PlanId = 3,
                            Descripcion = "50 Mbps/10 Mbps + 275 canales",
                            Estado = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5334),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5336),
                            Nombre = "Combo Premium",
                            Precio = 2850f,
                            TipoPlan = "Plan Premium",
                            TipoPlanId = 3
                        },
                        new
                        {
                            PlanId = 4,
                            Descripcion = "25 Mbps/5 Mbps + 225 canales",
                            Estado = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5439),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(5441),
                            Nombre = "Combo Deluxe",
                            Precio = 2500f,
                            TipoPlan = "Plan Premium",
                            TipoPlanId = 3
                        });
                });

            modelBuilder.Entity("Models.Tecnicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoCarnet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTecnico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoTecnicoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3108),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3112),
                            NoCarnet = "1234567891",
                            Nombre = "Tecnico1",
                            Telefono = "",
                            TipoTecnico = "",
                            TipoTecnicoId = 0,
                            Zona = "",
                            ZonaId = 0
                        },
                        new
                        {
                            Id = 2,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3230),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3234),
                            NoCarnet = "1234567892",
                            Nombre = "Tecnico2",
                            Telefono = "",
                            TipoTecnico = "",
                            TipoTecnicoId = 0,
                            Zona = "",
                            ZonaId = 0
                        },
                        new
                        {
                            Id = 3,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3319),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3323),
                            NoCarnet = "1234567893",
                            Nombre = "Tecnico3",
                            Telefono = "",
                            TipoTecnico = "",
                            TipoTecnicoId = 0,
                            Zona = "",
                            ZonaId = 0
                        },
                        new
                        {
                            Id = 4,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3401),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3404),
                            NoCarnet = "1234567894",
                            Nombre = "Tecnico4",
                            Telefono = "",
                            TipoTecnico = "",
                            TipoTecnicoId = 0,
                            Zona = "",
                            ZonaId = 0
                        },
                        new
                        {
                            Id = 5,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3494),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(3499),
                            NoCarnet = "1234567895",
                            Nombre = "Tecnico5",
                            Telefono = "",
                            TipoTecnico = "",
                            TipoTecnicoId = 0,
                            Zona = "",
                            ZonaId = 0
                        });
                });

            modelBuilder.Entity("Models.TipoAverias", b =>
                {
                    b.Property<int>("TipoAveriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAveria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoAveriaId");

                    b.ToTable("TipoAverias");

                    b.HasData(
                        new
                        {
                            TipoAveriaId = 1,
                            NombreAveria = "Fibra Rota"
                        },
                        new
                        {
                            TipoAveriaId = 2,
                            NombreAveria = "No Señal"
                        },
                        new
                        {
                            TipoAveriaId = 3,
                            NombreAveria = "Averia General"
                        });
                });

            modelBuilder.Entity("Models.TipoPagos", b =>
                {
                    b.Property<int>("TipoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoPagoId");

                    b.ToTable("TipoPagos");

                    b.HasData(
                        new
                        {
                            TipoPagoId = 1,
                            NombrePago = "Efectivo"
                        },
                        new
                        {
                            TipoPagoId = 2,
                            NombrePago = "Tarjeta"
                        },
                        new
                        {
                            TipoPagoId = 3,
                            NombrePago = "Cheque"
                        });
                });

            modelBuilder.Entity("Models.TipoPlanes", b =>
                {
                    b.Property<int>("TipoPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoPlanId");

                    b.ToTable("TipoPlanes");

                    b.HasData(
                        new
                        {
                            TipoPlanId = 1,
                            NombrePlan = "Plan Básico"
                        },
                        new
                        {
                            TipoPlanId = 2,
                            NombrePlan = "Plan Medio"
                        },
                        new
                        {
                            TipoPlanId = 3,
                            NombrePlan = "Plan Premium"
                        });
                });

            modelBuilder.Entity("Models.TipoUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Empleado común"
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Empleado Call Center"
                        });
                });

            modelBuilder.Entity("Models.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Existente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido = "Baltodano P",
                            Cedula = "402-3236649-1",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(1717),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(1753),
                            Nombre = "Luis Rafael",
                            Password = "20200070",
                            TipoUsuario = "",
                            TipoUsuarioId = 1,
                            UserName = "RafaelB"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Apellido = "Reyes",
                            Cedula = "402-3236649-2",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(1861),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(1864),
                            Nombre = "Jeison",
                            Password = "20190564",
                            TipoUsuario = "Administrador",
                            TipoUsuarioId = 1,
                            UserName = "JeisonR"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Apellido = "Duran T",
                            Cedula = "402-3236649-3",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(1942),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(1945),
                            Nombre = "Samuel",
                            Password = "20190793",
                            TipoUsuario = "Administrador",
                            TipoUsuarioId = 1,
                            UserName = "SamuelD"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Apellido = "Rosario",
                            Cedula = "402-3236649-4",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2015),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2019),
                            Nombre = "Elianny",
                            Password = "20190255",
                            TipoUsuario = "Administrador",
                            TipoUsuarioId = 1,
                            UserName = "EliannyR"
                        },
                        new
                        {
                            UsuarioId = 5,
                            Apellido = "Justo",
                            Cedula = "402-3236649-5",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2090),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2093),
                            Nombre = "Yunilda",
                            Password = "20190274",
                            TipoUsuario = "Administrador",
                            TipoUsuarioId = 1,
                            UserName = "YunildaJ"
                        },
                        new
                        {
                            UsuarioId = 6,
                            Apellido = "",
                            Cedula = "",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2178),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2181),
                            Nombre = "Usuario Admin",
                            TipoUsuario = "Administrador",
                            TipoUsuarioId = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            UsuarioId = 7,
                            Apellido = "",
                            Cedula = "",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2620),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2625),
                            Nombre = "Usuario comun",
                            Password = "comun",
                            TipoUsuario = "Usuario comun",
                            TipoUsuarioId = 2,
                            UserName = "comun"
                        },
                        new
                        {
                            UsuarioId = 8,
                            Apellido = "",
                            Cedula = "",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2700),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2703),
                            Nombre = "CallCenter",
                            Password = "call",
                            TipoUsuario = "Call center",
                            TipoUsuarioId = 3,
                            UserName = "call"
                        },
                        new
                        {
                            UsuarioId = 9,
                            Apellido = "",
                            Cedula = "402-3236649-9",
                            Existente = true,
                            FechaCreacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2771),
                            FechaModificacion = new DateTime(2022, 8, 6, 17, 49, 58, 924, DateTimeKind.Local).AddTicks(2774),
                            Nombre = "Freddy Belliard",
                            Password = "freddy1",
                            TipoUsuario = "Administrador",
                            TipoUsuarioId = 1,
                            UserName = "FreddyB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
