using System.ComponentModel.DataAnnotations;
using System;

namespace Models
{
	public class Contratos
	{
		[Key]
		public int? ContratoId { get; set; }
		public string NoContrato{ get; set; } = string.Empty; //AutoGenerated
		public DateTime FechaCreacion { get; set; } = DateTime.Now;
		public DateTime FechaModificacion { get; set; } = DateTime.Now;
		public string NombreCliente { get; set; } = string.Empty;
		public string ApellidoCliente { get; set; } = string.Empty;
		public string Cedula { get; set; } = string.Empty;
		public string Direccion { get; set; } = string.Empty;
		public string Celular { get; set; } = string.Empty;
		public string Telefono { get; set; } = string.Empty;
		public string? TelefonoReferencial { get; set; }
		public int PlanId { get; set; }
		public string Plan { get; set; } = string.Empty;
		public string? Comentario { get; set; }
	}
}