using System.ComponentModel.DataAnnotations;
using System;

namespace Models
{
    public class Pagos
    {
        [Key]
        public int? PagoId { get; set; } //Autogenerated
        public string NoContrato {get;set;}=string.Empty;
        public int TipoPagoId { get; set; }//Si es tarjeta, cheque, etc.
        public string NombreCliente { get; set; }= string.Empty;
        public string ApellidoCliente { get; set; }= string.Empty;
        public string CedulaCliente { get; set; }= string.Empty;
        public string TipoPago { get; set; } = string.Empty;//Si es tarjeta, cheque, etc.
        public float? MontoPago { get; set; }
        public string Asunto { get; set; } = string.Empty;// Si es solo pago de mensualidad, o reactivación etc etc
        public string Comentario { get; set; } = string.Empty;
        public DateTime FechaPago { get; set; } = DateTime.Now;// fecha del pago 
        public bool Existente { get; set; } = true;// si el pago existe en la base de datos o no
    }
}