using System.ComponentModel.DataAnnotations;
using System;

namespace Models
{
    public class Planes
    {
        [Key]
        public int? PlanId { get; set; } //Autogenerated
        public string Nombre { get; set; } = string.Empty;
        public float? Precio { get; set; }
        public DateTime FechaCreacion { get; set; } = DateTime.Now;
        public DateTime FechaModificacion { get; set; } =  DateTime.Now;
        public string Descripcion { get; set; } = string.Empty;
        public int TipoPlanId { get; set; }
        public bool Estado { get; set; } = true;//(false)Suspendido o (true)activo
        public bool Existente = true;// si el plan existe en la base de datos o no
    }
}